[supabase]
url = "https://zwjhqfjsqjnvhdegixjn.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3amhxZmpzcWpudmhkZWdpeGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3NTM5MDksImV4cCI6MjA4MDMyOTkwOX0.QIo4GNqd3yJylxop7cEp6FGnBz7No9Q1xkMItfDUB5k"
